steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile.api', '-t', 'gcr.io/$PROJECT_ID/grace-irvine-api', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/grace-irvine-api']
images:
- 'gcr.io/$PROJECT_ID/grace-irvine-api'
