coordinator_calendar:
  calendar_description: 事工通知发送提醒日历
  calendar_name: Grace Irvine 事工协调日历
  notification_times:
    monthly_overview: 09:00
    sunday_reminder: '20:00'
    weekly_confirmation: '20:00'
  subscribers:
  - coordinator@example.com
  timezone: America/Los_Angeles
output_directory: calendars/
sync_settings:
  auto_sync_enabled: true
  google_sheets_id: ''
  last_sync: '2025-08-26T15:07:48.210166'
  service_account_path: configs/service_account.json
  sync_frequency_hours: 12
worker_calendar:
  calendar_description: 个人事工服事安排日历
  calendar_name: Grace Irvine 同工服事日历
  notification_times:
    monthly_overview: 09:00
    sunday_reminder: '20:00'
    weekly_confirmation: '20:00'
  subscribers: []
  timezone: America/Los_Angeles
