spreadsheet_id: "1wescUQe9rIVLNcKdqmSLpzlAw9BGXMZmkFvjEF296nM"
sheet_name: "总表"
columns:
  date: "A"
  roles:
    - key: "Q"
      service_type: "音控"
    - key: "S"
      service_type: "导播/摄影"
    - key: "T"
      service_type: "ProPresenter播放"
    - key: "U"
      service_type: "ProPresenter更新"

# 云端存储配置
storage:
  # Bucket中的文件夹路径配置
  templates_path: "templates/"
  calendars_path: "calendars/"
  data_cache_path: "data/cache/"
  backups_path: "backups/"
  logs_path: "logs/"
